In [ ]:
import pandas as pd
import numpy as np 
url = 'https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv' 
df = pd.read_csv(url, encoding='latin1', sep=';')
df.columns

Index(['cisp', 'mes', 'ano', 'mes_ano', 'aisp', 'risp', 'munic', 'mcirc',
       'regiao', 'hom_doloso', 'lesao_corp_morte', 'latrocinio', 'cvli',
       'hom_por_interv_policial', 'feminicidio', 'letalidade_violenta',
       'tentat_hom', 'tentativa_feminicidio', 'lesao_corp_dolosa', 'estupro',
       'hom_culposo', 'lesao_corp_culposa', 'roubo_transeunte',
       'roubo_celular', 'roubo_em_coletivo', 'roubo_rua', 'roubo_veiculo',
       'roubo_carga', 'roubo_comercio', 'roubo_residencia', 'roubo_banco',
       'roubo_cx_eletronico', 'roubo_conducao_saque', 'roubo_apos_saque',
       'roubo_bicicleta', 'outros_roubos', 'total_roubos', 'furto_veiculos',
       'furto_transeunte', 'furto_coletivo', 'furto_celular',
       'furto_bicicleta', 'outros_furtos', 'total_furtos', 'sequestro',
       'extorsao', 'sequestro_relampago', 'estelionato', 'apreensao_drogas',
       'posse_drogas', 'trafico_drogas', 'apreensao_drogas_sem_autor',
       'recuperacao_veiculos', 'apf', 'aaapai', 'cmp', 'cmba', 'ameaca',
       'pessoas_desaparecidas', 'encontro_cadaver', 'encontro_ossada',
       'pol_militares_mortos_serv', 'pol_civis_mortos_serv',
       'registro_ocorrencias', 'fase'],
      dtype='str')

In [ ]:
df_roubo_veic_dp = df.groupby('cisp')['roubo_veiculo'].sum().reset_index()
df_roubo_veic_dp.sort_values(by='roubo_veiculo', ascending= False, inplace=True)

array_roubo_veic_dp = np.array(df_roubo_veic_dp['roubo_veiculo'])
media = np.mean(array_roubo_veic_dp)
mediana = np.median(array_roubo_veic_dp)
q1 = np.percentile(array_roubo_veic_dp, 25)
q2 = np.percentile(array_roubo_veic_dp, 50)
q3 = np.percentile(array_roubo_veic_dp, 75)

df_roubo_veic_dp_acima_q3 = df_roubo_veic_dp.loc[df_roubo_veic_dp['roubo_veiculo'] > q3]
#df_roubo_veic_dp_acima_q3
distancia = (media - mediana) / mediana # Número percentual por isso sai um decimal, depois é só formatar para %
# A distancia é puxada pelos valores extremos que afetam a media para cima ou para baixo, só lembrar das relações matemáticas. Literalmente pura matemática.
print(f'Média: {media}\nMediana: {mediana} \nDistânca: {distancia:.2%}') # Seja rigoroso com a distancia mas em projetos de portfolio use o letramento tecnico padrão

Média: 5250.840579710145
Mediana: 1227.0
Distânca: 327.94%

In [36]:
df_baixada = df.loc[df['regiao'] == 'Baixada Fluminense'] # Baixa Fluminense != Baixada
df_roubo_veic_dp_baixada = df_baixada.groupby('cisp')['roubo_veiculo'].sum().reset_index()
df_roubo_veic_dp_baixada.sort_values(by='roubo_veiculo', ascending= False, inplace=True)

array_roubo_veic_dp_baixada = np.array(df_roubo_veic_dp_baixada)
q1 = np.percentile(array_roubo_veic_dp_baixada, 25)
q2 = np.percentile(array_roubo_veic_dp_baixada, 50)
q3 = np.percentile(array_roubo_veic_dp_baixada, 75)

df_roubo_veic_dp_baixada = df_roubo_veic_dp_baixada.loc[df_roubo_veic_dp_baixada['roubo_veiculo'] > q3]
df_roubo_veic_dp_baixada

    cisp  roubo_veiculo
10    59          37780
15    64          32839
5     54          24945
11    60          20696
9     58          16351
3     52          15653
8     57          12516
7     56          12019
13    62           9279
4     53           8567

In [ ]:
df_ap_menores_dp = df.groupby('cisp')['aaapai'].sum().reset_index()
df_ap_menores_dp.sort_values(by='aaapai', ascending= False, inplace=True) 

array_ap_menores_dp = np.array(df_ap_menores_dp)
media = np.mean(array_ap_menores_dp)
mediana = np.median(array_ap_menores_dp)
distancia = (media - mediana) / mediana

print(f'Média: {media} \nMediana: {mediana} \nDistânca: {distancia:.2%}')

Média: 495.3804347826087
Mediana: 135.5
Distânca: 265.59%

In [ ]:
df_roubo_rua_dp = df.groupby('cisp')['roubo_rua'].sum().reset_index()
df_roubo_rua_dp.sort_values(by='roubo_rua', ascending= False, inplace=True) 

array_roubo_rua_dp = np.array(df_roubo_rua_dp)
media = np.mean(array_roubo_rua_dp)
mediana = np.median(array_roubo_rua_dp)
distancia = (media - mediana) / mediana
print(f'Média: {media} \nMediana: {mediana} \nDistânca: {distancia:.2%}')

df_roubo_rua_dp

Média: 6558.315217391304
Mediana: 134.5
Distânca: 4776.07%

     cisp  roubo_rua
52     59      87859
57     64      64737
30     34      58326
25     29      50126
65     74      47594
..    ...        ...
131   157         16
130   156         11
94    111          7
77     92          6
129   155          5

[138 rows x 2 columns]