In [22]:
import pandas as pd
import numpy as np # Calculos otimizados

In [12]:
# Em alguns casos não tem o link
url = 'https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv' # Se você usa URL não precisa de CSV, e assim o CSV sempre vai atualizar em tempo real. 
# Cisp == num DP; MCIRC == codigo do municipio do IBGE; 

df = pd.read_csv(url, encoding='latin1', sep=';') # Na maioria dos casos quando o UTF-8 não é o encoder o latin1 é a solução
# .head(), é usado para testes e puxa somente a quantidade de linhas que você quer. Sem nenhum parametro ele chama 5 linhas; .tail(), é o inverso do head.
# .columns lista colunas; .info() diz a coluna e a quantidade de dados não nulos e tipo de dados de cada coluna
df.columns

Index(['cisp', 'mes', 'ano', 'mes_ano', 'aisp', 'risp', 'munic', 'mcirc',
       'regiao', 'hom_doloso', 'lesao_corp_morte', 'latrocinio', 'cvli',
       'hom_por_interv_policial', 'feminicidio', 'letalidade_violenta',
       'tentat_hom', 'tentativa_feminicidio', 'lesao_corp_dolosa', 'estupro',
       'hom_culposo', 'lesao_corp_culposa', 'roubo_transeunte',
       'roubo_celular', 'roubo_em_coletivo', 'roubo_rua', 'roubo_veiculo',
       'roubo_carga', 'roubo_comercio', 'roubo_residencia', 'roubo_banco',
       'roubo_cx_eletronico', 'roubo_conducao_saque', 'roubo_apos_saque',
       'roubo_bicicleta', 'outros_roubos', 'total_roubos', 'furto_veiculos',
       'furto_transeunte', 'furto_coletivo', 'furto_celular',
       'furto_bicicleta', 'outros_furtos', 'total_furtos', 'sequestro',
       'extorsao', 'sequestro_relampago', 'estelionato', 'apreensao_drogas',
       'posse_drogas', 'trafico_drogas', 'apreensao_drogas_sem_autor',
       'recuperacao_veiculos', 'apf', 'aaapai', 'cmp', 'cmba', 'ameaca',
       'pessoas_desaparecidas', 'encontro_cadaver', 'encontro_ossada',
       'pol_militares_mortos_serv', 'pol_civis_mortos_serv',
       'registro_ocorrencias', 'fase'],
      dtype='str')

In [3]:
# Qualitativo no parentese e quantitativo colchete, reset_index() faz com que o index não seja o valor qualitativo
df_furto_cel_dp = df.groupby('cisp')['furto_celular'].sum().reset_index() 
df_furto_cel_dp = df_furto_cel_dp.sort_values(by='furto_celular', ascending= False) # ascending define a relação, default vem true (crescente e decrescente)
df_furto_cel_dp

     cisp  furto_celular
12     16          26111
2       5          25440
10     14          18822
8      12          17537
0       1          16127
..    ...            ...
87    104             73
77     92             65
114   138             56
131   157             55
129   155             47

[138 rows x 2 columns]

In [ ]:
df_ap_menores_dp = df.groupby('cisp')[['aaapai', 'cmba']].sum().reset_index()
df_ap_menores_dp.sort_values(by='aaapai', ascending= False, inplace=True) # Inplace deixa a mudança permanente, isso ajuda a não repetir a igualdade df = df 
df_ap_menores_dp

     cisp  aaapai    cmba
104   126  3713.0   119.0
8      12  3657.0  1089.0
10     14  3365.0   727.0
65     74  3349.0   192.0
12     16  3218.0   844.0
..    ...     ...     ...
130   156    19.0     3.0
129   155    16.0     3.0
131   157    14.0     3.0
94    111    13.0     3.0
77     92    12.0     2.0

[138 rows x 3 columns]

In [5]:
df_roubo_vei_dp = df.groupby('cisp')['roubo_veiculo'].sum().reset_index()
df_roubo_vei_dp = df_roubo_vei_dp.sort_values(by='roubo_veiculo', ascending=False)
df_roubo_vei_dp

     cisp  roubo_veiculo
52     59          37780
57     64          32839
35     39          29663
23     27          27920
30     34          27543
..    ...            ...
77     92              8
116   140              8
115   139              7
113   137              6
114   138              2

[138 rows x 2 columns]

In [ ]:
# Filtros diferentes: 
df_capital = df[df['munic'] == 'Rio de Janeiro'] # Dataframe onde a coluna de munic é apenas a capital
# Esses dois tem o desempenho melhor
df_capital = df.query("munic == 'Rio de Janeiro'") # Query onde a condicional inteira está em string, mais complicado porque é fácil de se confundir com as aspas
df_capital = df.loc[df['munic'] == 'Rio de Janeiro'] # Mesma coisa que o primeiro, só que o loc é melhor porque tem a sintaxe parecida com outras.

df_furto_cel_dp_capital = df_capital.groupby('cisp')['furto_celular'].sum().reset_index()
df_furto_cel_dp_capital.sort_values(by='furto_celular', ascending=False, inplace=True)
df_furto_cel_dp_capital

In [ ]:
munic_pedido = ['Belford Roxo', 'Nova Iguaçu', 'Queimados']
# isin é feito para fazer um filtro usando uma lista com base, o separador de condições é '&' e as condições ficam em parenteses 
df_bel_nov_quei = df.loc[((df['munic'].isin(munic_pedido)) & (df['ano'] == 2025))]

df_roxo_furto_cel_dp = df_bel_nov_quei.groupby('cisp')['furto_celular'].sum().reset_index()
df_roxo_furto_cel_dp.sort_values(by='furto_celular', ascending=False, inplace=True)
df_roxo_furto_cel_dp

   cisp  furto_celular
0    52            519
4    58            188
3    56            123
1    54            112
2    55             96

In [ ]:
array_furto_cel_dp = np.array(df_furto_cel_dp['furto_celular']) # array para os calculos de np

media = np.mean(array_furto_cel_dp)
mediana = np.median(array_furto_cel_dp) # Mesma mediana da escola
# Quartis: São as porcentagens no caso linhas de corte, q1(25%), q2(50% e sempre vai ser igual a mediana) e q3(75%). 
# Eles são chamados de quartis porque dividem em 4 parcelas de 25%
# Se você muda a porcentagem ele deixa de ser um quatil e passa a ser uma análise pessoal
q1 = np.percentile(array_furto_cel_dp, 25)
q2 = np.percentile(array_furto_cel_dp, 50)
q3 = np.percentile(array_furto_cel_dp, 75)
print(f'Média: {media}\nMediana: {mediana}')
print(f'Q1: {q1} \nQ2: {q2} \nQ3: {q3}')

Média: 3534.014492753623
Mediana: 1729.0
Q1: 455.0
Q2: 1729.0
Q3: 4694.0

In [32]:
df_furto_cel_acima_q3 = df_furto_cel_dp.loc[df_furto_cel_dp['furto_celular'] > q3] 
df_furto_cel_acima_q3 = df_furto_cel_dp.query('furto_celular > @q3') # No query você precisa usar @ para chamar uma variavel
df_furto_cel_acima_q3

     cisp  furto_celular
12     16          26111
2       5          25440
10     14          18822
8      12          17537
0       1          16127
5       9          15278
6      10          14773
14     18          14436
1       4          14247
28     32          12833
31     35          12231
15     19           8899
52     59           8849
13     17           8701
67     76           8342
25     29           8223
38     42           8132
9      13           7804
19     23           7360
11     15           7261
17     21           7040
30     34           6971
33     37           6669
3       6           6617
29     33           6185
18     22           5770
45     52           5655
32     36           5596
37     41           5458
16     20           5357
68     77           5041
104   126           4979
20     24           4758
65     74           4755
23     27           4708