In [1]:
import pandas as pd

In [22]:
# Em alguns casos não tem o link
url = 'https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv' # Se você usa URL não precisa de CSV, e assim o CSV sempre vai atualizar em tempo real. 
# Cisp == num DP; MCIRC == codigo do municipio do IBGE; 

df = pd.read_csv(url, encoding='latin1', sep=';') # Na maioria dos casos quando o UTF-8 não é o encoder o latin1 é a solução
# .head(), é usado para testes e puxa somente a quantidade de linhas que você quer. Sem nenhum parametro ele chama 5 linhas; .tail(), é o inverso do head.
# .columns lista colunas; .info() diz a coluna e a quantidade de dados não nulos e tipo de dados de cada coluna
df.columns

Index(['cisp', 'mes', 'ano', 'mes_ano', 'aisp', 'risp', 'munic', 'mcirc',
       'regiao', 'hom_doloso', 'lesao_corp_morte', 'latrocinio', 'cvli',
       'hom_por_interv_policial', 'feminicidio', 'letalidade_violenta',
       'tentat_hom', 'tentativa_feminicidio', 'lesao_corp_dolosa', 'estupro',
       'hom_culposo', 'lesao_corp_culposa', 'roubo_transeunte',
       'roubo_celular', 'roubo_em_coletivo', 'roubo_rua', 'roubo_veiculo',
       'roubo_carga', 'roubo_comercio', 'roubo_residencia', 'roubo_banco',
       'roubo_cx_eletronico', 'roubo_conducao_saque', 'roubo_apos_saque',
       'roubo_bicicleta', 'outros_roubos', 'total_roubos', 'furto_veiculos',
       'furto_transeunte', 'furto_coletivo', 'furto_celular',
       'furto_bicicleta', 'outros_furtos', 'total_furtos', 'sequestro',
       'extorsao', 'sequestro_relampago', 'estelionato', 'apreensao_drogas',
       'posse_drogas', 'trafico_drogas', 'apreensao_drogas_sem_autor',
       'recuperacao_veiculos', 'apf', 'aaapai', 'cmp', 'cmba', 'ameaca',
       'pessoas_desaparecidas', 'encontro_cadaver', 'encontro_ossada',
       'pol_militares_mortos_serv', 'pol_civis_mortos_serv',
       'registro_ocorrencias', 'fase'],
      dtype='str')

In [34]:
# Qualitativo no parentese e quantitativo colchete, reset_index() faz com que o index não seja o valor qualitativo
df_furto_cel_dp = df.groupby('cisp')['furto_celular'].sum().reset_index() 
df_furto_cel_dp = df_furto_cel_dp.sort_values(by='furto_celular', ascending= False) # ascending define a relação, default vem true (crescente e decrescente)
df_furto_cel_dp

     cisp  furto_celular
12     16          26111
2       5          25440
10     14          18822
8      12          17537
0       1          16127
..    ...            ...
87    104             73
77     92             65
114   138             56
131   157             55
129   155             47

[138 rows x 2 columns]

In [33]:
df_ap_menores_dp = df.groupby('cisp')['aaapai'].sum().reset_index()
df_ap_menores_dp = df_ap_menores_dp.sort_values(by='aaapai', ascending= False)
df_ap_menores_dp

     cisp  aaapai
104   126  3713.0
8      12  3657.0
10     14  3365.0
65     74  3349.0
12     16  3218.0
..    ...     ...
130   156    19.0
129   155    16.0
131   157    14.0
94    111    13.0
77     92    12.0

[138 rows x 2 columns]

In [30]:
df_roubo_vei_dp = df.groupby('cisp')['roubo_veiculo'].sum().reset_index()
df_roubo_vei_dp = df_roubo_vei_dp.sort_values(by='roubo_veiculo', ascending=False)
df_roubo_vei_dp

     cisp  roubo_veiculo
52     59          37780
57     64          32839
35     39          29663
23     27          27920
30     34          27543
..    ...            ...
77     92              8
116   140              8
115   139              7
113   137              6
114   138              2

[138 rows x 2 columns]